project:
  type: book

book:
  title: "web_book"
  author: "Norah Jones"
  date: "7/17/2024"
  chapters:
    - index.qmd
    - education.qmd
    - work_positions.qmd
    - peer-reviewed_pubs.qmd
    - presentations.qmd
    - invited_presentations.qmd
    - teaching_experience.qmd
    - professional_service.qmd
    - awards.qmd
    - funding.qmd
    - popular_outreach.qmd
    - training_skills.qmd
    - memberships.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

