project:
  type: book

book:
  title: "web_book"
  author: "Norah Jones"
  date: "7/17/2024"
  chapters:
    - index.qmd
    - section-education.qmd
    - section-work_positions.qmd
    - section-peer-reviewed_pubs.qmd
    - section-presentations.qmd
    - section-invited_presentations.qmd
    - section-teaching_experience.qmd
    - section-professional_service.qmd
    - section-awards.qmd
    - section-funding.qmd
    - section-popular_outreach.qmd
    - section-training_skills.qmd
    - section-memberships.qmd

bibliography: section-peer-reviewed_pubs.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

