project:
  type: book
  output-dir: _book
book:
  title: "Curriculum vitae"
  author: "Claire M. Curry"
  search: true
  downloads: [pdf]
  date: last-modified
  page-navigation: true
  chapters:
    - index.qmd
    # - section-education.qmd
    # - section-work_positions.qmd
    # - section-teaching_experience.qmd
    # - section-products.qmd
    # - section-professional_service.qmd
    # - section-awards.qmd
    # - section-funding.qmd
    # - section-memberships.qmd
    # - section-training_skills.qmd

#https://www.andrewheiss.com/blog/2023/12/11/separate-bibliographies-quarto/

# filters:
#   - multibib
# validate-yaml: false
# 
# citeproc: false

number-depth: 2

bibliography: refs-peer-reviewed_pubs.bib
csl: council-of-science-editors_text.csl

format:
  html:
    toc: false
    code-background: true
    code-copy: true
    css: style.css
    fontsize: 12pt
    reference-location: margin
    link-citations: false
    #citation-location: margin
  docx:
    toc: false
    number-sections: true
  pdf:
    documentclass: scrreprt
# https://tex.stackexchange.com/questions/36988/regarding-the-book-report-and-article-document-classes-what-are-the-mai
# scrreprt gets rid of chapter titles https://cameronpatrick.com/post/2023/07/quarto-thesis-formatting/
    toc: false
    link-citations: false
    number-sections: true
    keep-tex: false
    geometry:
      - papersize=letter

# nocite: |
#    @shortkey, @shortkey2
  
editor: source

#https://forums.zotero.org/discussion/38693/insert-a-full-bibliographic-entry-through-the-insert-citation-function
