---
title: CV
format:
  quarto-cv-pdf: default
author: Claire M. Curry
date: last-modified
#phone: 940-600-8362
address: "Phone: +1 405-325-5385 · Mail: 401 W. Brooks St. · Norman, OK, 73019, USA"
email: cmcurry@ou.edu
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
github: baeolophus #github account username
orcid: 0000-0003-4649-7537 # orcid identifier
#osf: 94hfg # osf five character id
#twitter: twitter # twitter handle
web: cmcurry.com
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: refs-peer-reviewed_pubs.bib
  reports: refs-reports.bib
  conference: refs-conferences.bib
  invited: refs-invited.bib
  popular: refs-popular.bib
  public_talks: refs-public_talks.bib
validate-yaml: false
csl: apa-cv.csl
#Make my name bold in bibligographies using lua filter https://tex.stackexchange.com/questions/33330/make-one-authors-name-bold-every-time-it-shows-up-in-the-bibliography
filters:
  - bold-author.lua
bold-auth-name:
  - family: Curry
    given: C. M.
  - family: Curry
    given: Claire
  - family: Curry
    given: C.  
format:
  quarto-cv-pdf: default
---


# Summary

I guide higher education students, faculty, and staff to enhance their research, teaching, and learning work through group and individual instruction on information literacy, data literacy, and reproducible research methods.


# Education

*University of Oklahoma (OU)* Ph.D. in Ecology and Evolutionary Biology (Zoology) <span> \color{lightgray} \dotfill </span> 2008-2014

-   Dissertation: "The evolution of reproductive isolation in a temporally complex passerine hybrid zone"
-   Advisor: Dr. Michael A. Patten

*University of North Texas (UNT)* B.S. in Biology, Chemistry minor (summa cum laude) <span> \color{lightgray} \dotfill </span> 2005-2007

-   Honors thesis: "Factors affecting interaction rates and space use of *Plathemis lydia* (Odonata: Libellulidae)"
-   Advisor: Dr. James H. Kennedy

# Employment

*University Libraries, University of Oklahoma (Norman, OK, USA)*

-   Science Librarian <span> \color{lightgray} \dotfill </span> 2018-present

*Oklahoma Biological Survey, University of Oklahoma (Norman, OK, USA)*

-   Post-doctoral Research Associate <span> \color{lightgray} \dotfill </span> 2016-2018

*Natural Resources Institute, University of Manitoba (UM), (Winnipeg, MB, Canada)*

-   Research Associate <span> \color{lightgray} \dotfill </span> 2016

-   Post-doctoral Fellow <span> \color{lightgray} \dotfill </span> 2014-2016

*U.S. Forest Service Contractor (Decatur, TX, USA)*

-   Contractor for Lyndon B. Johnson National Grasslands <span> \color{lightgray} \dotfill </span> March-June 2008

-   Contractor for Lyndon B. Johnson National Grasslands <span> \color{lightgray} \dotfill </span> December 2001-February 2002

*Aquatic Ecology Lab, University of North Texas (Denton, TX, USA)*

-   Undergraduate Research Assistant <span> \color{lightgray} \dotfill </span> March-August 2007

-   Undergraduate Research Assistant <span> \color{lightgray} \dotfill </span> October 2005-May 2006

*Leon River Restoration Project (with Texas A&M University)*

-   Seasonal Field Biologist <span> \color{lightgray} \dotfill </span> May-July 2006

*Texas Agricultural Experiment Station (Vernon, TX, USA)*

-   Field Technician <span> \color{lightgray} \dotfill </span> June-August 2005

{{< pagebreak >}}

# Teaching Experience

## Research Data Workshops  <span> \color{lightgray} \dotfill </span> 2017-present

Teach, develop, and adapt curricula independently and collaboratively to enhance researchers' abilities to process, analyze, and visualize information.

- *Custom lessons*

  - Repetitive Tasks in R

  ::: {.content-hidden}

  \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Adapted and expanded from Software Carpentry R lesson

  :::

  - Visualization in R Using 'ggplot2'

  ::: {.content-hidden}

    \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Adapted and expanded from Data Carpentry R lesson and organized around our data visualizations concept workshop (next entry)

  :::

  - Survival Skills: Concepts of Data-Driven Visualization

  - Survival Skills: Using Computers for Scholarly Research

  - Smoother Meetings: Tips from Your Librarians

  - A Very Short Introduction to Geospatial R

  ::: {.content-hidden}
  
    \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Adapted and shortened from Data Carpentry lessons into three  50-min lessons for cross-listed undergraduate/graduate course visits
  
  :::



  - A Very Short Introduction to R


  ::: {.content-hidden}
  
    \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Adapted and shortened from Data Carpentry lesson into one 1.25 hr session
  
    \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Created modular .Rmd files to allow mix and match of lesson chunks for two different class visits (one for a cross-listed graduate/undergraduate class, and another for a senior-level undergraduate class)
  
  :::


  - Survival Skills: Managing Research Files

  - Citation Management with Zotero

  - Managing Research Projects with OSF

  - Survival Skills: Troubleshooting Computer Code


  ::: {.content-hidden}
  
  *Maintain and update workshops in collaboration with colleagues* <span> \color{lightgray} \dotfill </span> 2018-present
  
  ::: 



  - Formatting Your Data for Analysis

  
  ::: {.content-hidden}
  
    \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Adapted and shortened from Data Carpentry "tidy data" lesson
  
  *Instructing from existing curricula* <span> \color{lightgray} \dotfill </span> 2017-present
  
  :::

- *Data Carpentry Lessons*

  - Data Analysis and Visualisation in R for Ecologists
  
  ::: {.content-hidden}


  \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Including modifications for 1.25-2.5 hr short version for course instruction
  
  :::

  
  - R for Social Sciences

  - Introduction to R for Geospatial Data
  
  ::: {.content-hidden}

    - \cdot \nobreakspace Including modifications for 2.5 hr two-session shorter version

  :::


  - Data Organization in Spreadsheets for Ecologists

  - Data Management with SQL for Ecologists

  - Data Cleaning with OpenRefine for Ecologists

- *Software Carpentry Lessons*

  - R for Scientific Programming
  
  - Unix Shell (Bash) for Beginners
  
  - Tracking Changes with Version Control in Git/GitHub


## Library Instruction  <span> \color{lightgray} \dotfill </span> 2018-present


Incorporating Carpentries instructor training around motivational language and cognitive load into my instructional approach. Updating all classroom and asynchronous materials to improve accessibility.

- *Data, reference, and statistical consultations*   <span> \color{lightgray} \dotfill </span> 1,842 consultations

::: {.content-hidden}
  - \cdot \nobreakspace 380 faculty sessions
  - \cdot \nobreakspace 898 graduate student sessions
  - \cdot \nobreakspace 135 post-docs/researcher sessions
  - \cdot \nobreakspace 101 staff sessions
  - \cdot \nobreakspace 233 undergraduate students sessions
  - \cdot \nobreakspace 95 other and unknown sessions
:::




- *Information literacy and library resource introductions for STEM courses*  <span> \color{lightgray} \dotfill </span> 220 sessions



::: {.content-hidden}

Reached 4,010 learners since July 2018

- \bullet \nobreakspace Teach, develop, and scaffold information literacy skills to undergraduate and graduate STEM students

- \bullet \nobreakspace Develop and deliver one-shot and multiple visit teaching sessions about search tools, information literacy, and library resources

- \bullet \nobreakspace Develop new exercises and materials to teach information literacy skills in subject-specific examples in collaboration with instructors

- \bullet \nobreakspace Using ACRL Information Literacy for STEM guidelines to frame scaffolding suggestions within STEM degrees

- *Introduction to library resources and OU Libraries welcome presentations*


\hangindent=0.5em \hangafter=1 \bullet \nobreakspace  Orientations and professional development classes for graduate STEM programs

\hangindent=0.5em \hangafter=1 \bullet \nobreakspace   First Year Research Experience class

- \bullet \nobreakspace On request by course instructors

:::

- *Video series for STEM remote research method options* <span> \color{lightgray} \dotfill </span> 27 videos

::: {.content-hidden}

    -  \cdot \nobreakspace   Created, produced, and transcribed 27 videos during initial university closure during COVID pandemic in summer 2020
    
    -  \cdot \nobreakspace   Hosted lecture on meta-analysis

    -  \cdot \nobreakspace   Presented videos on data licensing, finding datasets, and literature searches

    -  \cdot \nobreakspace   Solicited guest appearances from campus partners like OU Writing Center, Expository Writing Program, and Center for Faculty Excellence

:::

- *"Why Cite?" Tutorial* <span> \color{lightgray} \dotfill </span> video with quiz

::: {.content-hidden}

    -  \cdot \nobreakspace  to explain necessary parts and rationale for citations beyond avoiding plagiarism

:::

- *OU Libraries LibGuides* <span> \color{lightgray} \dotfill </span> assigned STEM subjects

::: {.content-hidden}
\hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Updating subject guides for my departments
:::

- *Research Data and Data Management LibGuides* <span> \color{lightgray} \dotfill </span> 3 guides

::: {.content-hidden}

- \cdot \nobreakspace   Data Analysis & Visualization

- \cdot \nobreakspace   Research Survival Skills (shared, based on "Survival Skills" workshop series)

- \cdot \nobreakspace  Citation Management with Zotero (shared)

:::


  


## Instructor of Record

*NRI7350: Study Design & Quantitative Methods for Resource & Environmental Management (cross-listed, UM)*

- Co-instructor with Dr. Nicola Koper  <span> \color{lightgray} \dotfill </span> winters 2015, 2016


::: {.content-hidden}


-  \bullet \nobreakspace   Presenting R code to implement statistical methods; lecture on multivariate statistics; and grading half of assignments

:::

*NRI7273: Ecological Dimensions of Natural Resource Management (graduate, UM)* <span> \color{lightgray} \dotfill </span> fall 2015


::: {.content-hidden}

-  \bullet \nobreakspace   Sessional instructor: Lecture, guide discussions, grade assignments

:::

## Mentoring

*UM Students* <span> \color{lightgray} \dotfill </span> 2014-2016

-  Experimental design - Master’s (16), undergraduate (1), and Ph.D. (2) students in two departments

::: {.content-hidden}


-  \bullet \nobreakspace   Guidance on project design, sampling, statistical analysis, and use of R and SAS for Master’s (14), undergraduate (1), and Ph.D. (1) students in Dr. Nicola Koper lab

-  \bullet \nobreakspace   Master’s (2) and Ph.D. (1) students at the Natural Resources Institute and Biology departments.

:::

*OU Students*

- Independent study: Alexandra Ainsworth (undergraduate) <span> \color{lightgray} \dotfill </span> spring 2012


::: {.content-hidden}

  -  \bullet \nobreakspace   Independent study (3 credit hours), PI: Dr. Michael A. Patten

  -  \bullet \nobreakspace   She fed captive birds, assisted with mate choice trial set-up, bird capture, DNA extraction using Qiagen DNeasy kits, PCR, and agarose gel electrophoresis.

:::

- Volunteer: Sarai H. Stuart (post-graduate) <span> \color{lightgray} \dotfill </span> 2012-2013


::: {.content-hidden}
January-April 2012, January-March 2013

  -  \bullet \nobreakspace Volunteer

  -  \bullet \nobreakspace Recent OU graduate wanting field experience before applying to jobs and/or graduate school. She learned about mist-netting, trapping, banding, setting up mate choice trials, maintaining captive birds, DNA extraction using Qiagen DNeasy kits, PCR, and agarose gel electrophoresis. Graduated with Ph.D. from University of Illinois at Champaign-Urbana.

:::

*External Students*

- Undergraduate Diversity Mentor (2 mentees) at Evolution 2013 Conference in Snowbird, UT <span> \color{lightgray} \dotfill </span> 2013

## Graduate Teaching Assistantships

*BIOL1134: Intro. to Evolution, Ecology, and Diversity Lab (undergraduate majors, OU)* <span> \color{lightgray} \dotfill </span> spring 2012

::: {.content-hidden}

-  \bullet \nobreakspace Professor: Dr. Phil Gibson

-  \bullet \nobreakspace Presentation of weekly lab materials, creating and grading quizzes, grading lecture exams, proctoring lecture and lab exams, and guiding students through lab experiments.

:::

*BIOL4073/5073: General Entomology Lab (cross-listed, OU)* <span> \color{lightgray} \dotfill </span> 2009-2012 (fall only - total four semesters)

::: {.content-hidden}

-  \bullet \nobreakspace   Professor: Dr. Ken Hobson (retired)

-  \bullet \nobreakspace   Presentation of insect orders and families; creating and grading quizzes and exam; and leading students on field trips

:::

*ZOO1121: Introductory Zoology Lab (undergraduate non-majors, OU)* <span> \color{lightgray} \dotfill </span> fall 2008, fall 2012


::: {.content-hidden}


- Professor: Dr. Penny Hopkins (retired)

-  \bullet \nobreakspace   Lecturing on the day’s lab topic, assisting students with dissections, and writing, administering, and grading quizzes

:::

*BIOL3403: Principles of Ecology Lab (undergraduate majors, OU)* <span> \color{lightgray} \dotfill </span> 2009 (spring & fall), 2010-2011 (fall only)

::: {.content-hidden}

- Professor: Dr. Ken Hobson (retired)

-  \bullet \nobreakspace   Discussion of concepts, guiding students through field experiments; and grading lab reports.

:::

## Undergraduate Teaching Assistantship

*BIOL4070/5070: Insect Biology Lab (cross-listed, UNT), volunteer* <span> \color{lightgray} \dotfill </span> fall 2006, fall 2007


::: {.content-hidden}

- Professor: Dr. James Kennedy

- Volunteer


-  \bullet \nobreakspace   Help students with keying insects, assist students on field trips, and proctor exams and quizzes with the graduate teaching assistants.

:::

{{< pagebreak >}}


# Training and Skills

## Skills

- *Learner-Centered Flexible Pedagogy*

  - I work to empower learners to gain new skills and confidence. I incorporate motivational language and decrease cognitive load wherever possible, following Carpentries instructor practices. My materials incorporate active learning and follow universal design principles for accessibility that fit the teaching modality (virtual, in-person, or hybrid).


- *Working with People and Organizations*

    - Work with students, post-docs, staff, faculty, and community members

    - Collaborate with campus partner organizations and co-workers
    
    - Maintain communications with departmental representatives
    
      - \cdot \nobreakspace  School of Biological Sciences

      - \cdot \nobreakspace  Oklahoma Biological Station

      - \cdot \nobreakspace  Department of Geography & Environmental Sustainability

      - \cdot \nobreakspace  Psychology (shared)

      - \cdot \nobreakspace  Health & Exercise Science (shared)

      - \cdot \nobreakspace  Chemistry & Biochemistry (shared)


    - Obtain permission and maintain good relationships for field work
    
      - \cdot \nobreakspace  Privately owned land (US and Canada)
    
      - \cdot \nobreakspace  State-owned land (US)
    
      - \cdot \nobreakspace  Federal land (US)

    - Obtain permitting for avian research at university, state, provincial, and federal (US and Canada) levels


- *Statistical and Data Consulting*

    - Experimental design for field and lab work

    - Data collection and management

    - Univariate and multivariate statistical analysis
  
      - \cdot \nobreakspace Choice of approaches (frequentist and model selection)
  
      - \cdot \nobreakspace Choice and guidance on specific statistical tests
  
      - \cdot \nobreakspace Guidance searching discipline-specific literature for discipline-preferred approaches
  
      - \cdot \nobreakspace Choice and use of statistical programming software


- *Collection Management*

  - Assessing collection needs for new academic degrees and certificates

  - Approving book purchase requests

  - Analyzing usage to determine journal subscriptions and cancellations

  - Coordinating journal subscription requests among interested departments


## Software

- *Statistical Programs*

  - R 4.0+, as well as older versions through 3.6

  - SAS 9.2+

  - IBM SPSS Statistics 29+

- *Geographic Information Systems (GIS)*

  - R packages for GIS
  
  - Quantum GIS v. 2.10+
  
  - ESRI ArcGIS 9.2+
  
    - \cdot \nobreakspace   Maintain good relationship with vendor representatives at OU
  
    - \cdot \nobreakspace   Organized training to help users migrate to new ArcGIS Pro <span> \color{lightgray} \dotfill </span> 2023
  
    - \cdot \nobreakspace   Completed Introduction to GIS course (UNT) <span> \color{lightgray} \dotfill </span> fall 2007
  
- *Graphics and Data Visualization*

  - R packages including
  
    - \cdot \nobreakspace `ggplot2`
  
    - \cdot \nobreakspace `ggparty`
    
    - \cdot \nobreakspace `RShiny`
  
  - Inkscape 0.48+

- *Data Management and Processing*

  - Data wrangling

    - \cdot \nobreakspace   R `tidyverse`

    - \cdot \nobreakspace   OpenRefine
  
  - Version control
    
    - \cdot \nobreakspace   Git for Windows, Linux, Mac
    
    - \cdot \nobreakspace   GitHub.com
    
    - \cdot \nobreakspace   Git Large File System for Windows
    
  - Databases
        
    - \cdot \nobreakspace   SQLite
    
    - \cdot \nobreakspace   DB Browser for SQLite
      
    - \cdot \nobreakspace   PostgreSQL database language (queries, import and export of data)
        
    - \cdot \nobreakspace   pgAdmin III database interface and psql command line interface for use with PostgreSQL

    - \cdot \nobreakspace   jetSQL (Microsoft Access)

- *Citation Management*

  - Zotero 3.0.7+ bibliography software

- *Word Processing and Spreadsheets*

  - Microsoft Office 365
  
      - \cdot \nobreakspace   Word 
      
      - \cdot \nobreakspace   Access
      
      - \cdot \nobreakspace   Excel
      
      - \cdot \nobreakspace   PowerPoint
      
      - \cdot \nobreakspace   OneNote

  - LibreOffice 3.3.0+
  
      - \cdot \nobreakspace Writer (Word equivalent)  
  
      - \cdot \nobreakspace Impress (PowerPoint equivalent)  
  
      - \cdot \nobreakspace Base (Access equivalent)

- *Specialized Software*

  - Raven Pro 1.5 sound analysis software

  - Phylogenetic software (basic procedures)
  
      - \cdot \nobreakspace   MRBAYES 3.1.2
      
      - \cdot \nobreakspace   RAxML
      
      - \cdot \nobreakspace   GARLI 1.0
      
      - \cdot \nobreakspace   FigTree
      
      - \cdot \nobreakspace   MEGA 4.0

## Research Methods

- *Library and Literature-Based Methods*

  - Reproducible database searches

    - \cdot \nobreakspace   Explaining controlled vocabulary and thesaurus searches

    - \cdot \nobreakspace   Choosing and modifying keywords

    - \cdot \nobreakspace  Explaining Boolean operators and wild cards
  
  - Evidence synthesis

    - \cdot \nobreakspace   Guiding OU community members from multiple departments
  
    - \cdot \nobreakspace   Developing Evidence Synthesis LibGuide Page for initial information for community members
  
    - \cdot \nobreakspace   Collaborating with Writing Center on a future questionnaire to guide users to specific types of synthesis


::: {.content-hidden}
   
    - \cdot \ nobreakspace  Social Work, Mathematics, Health and Exercise Science, Geography & Environmental Sustainability, Education

:::


*Discipline-Specific Methods*

- *Experimental Design*

  - Design and conduct surveys
  
    - \cdot \nobreakspace Randomized stratified point counts for lichens
    
    - \cdot \nobreakspace Behavioral assays for songbirds
    
    - \cdot \nobreakspace Transect and point counts for grassland and shrubland birds

  
- *Field Methods*

  - Avian blood sampling for genetics
  
  - Banding and color-banding small songbirds

  - Nest and fledgling searching for grassland and shrubland birds
    
  - Terrestrial insect sampling

  - Sorting and identification of aquatic invertebrates

  - Habitat and vegetation measurements



- *Selected Trainings Attended*

  - Suicide Prevention (OU Military Support Forum Green Zone) <span> \color{lightgray} \dotfill </span> 2023

  - OU Green Zone (Veteran Support Center) <span> \color{lightgray} \dotfill </span> 2023

  - Navigating Tough Conversations in Statistical Collaboration Workshop <span> \color{lightgray} \dotfill </span> 2023
    
    - \cdot \nobreakspace Oklahoma Chapter of the American Statistical Association

  - Evidence Synthesis Institute (by application only) <span> \color{lightgray} \dotfill </span> August 2022

  - ACRL Framework <span> \color{lightgray} \dotfill </span> 2022
  
    - \cdot \nobreakspace Association of College & Research Libraries Framework Virtual Workshop for OU Libraries

  - American Heart Association CPR/AED Course for Adult, Child, Infant <span> \color{lightgray} \dotfill </span> 2022

  - American College of Surgeons STOP THE BLEED <span> \color{lightgray} \dotfill </span> 2022

  - Institutional Review Board <span> \color{lightgray} \dotfill </span> 2020

  - Diversity Ally Training (OU HR) <span> \color{lightgray} \dotfill </span> 2019
    
    - \cdot \nobreakspace Unlearning Ableism
    
    - \cdot \nobreakspace Unlearning Classism
    
    - \cdot \nobreakspace Unlearning Racism

  - Mental Health First Aid <span> \color{lightgray} \dotfill </span> 2019

  - Software/Data Carpentries Instructor Training <span> \color{lightgray} \dotfill </span> 2018

  - Question, Persuade, Refer, Suicide Prevention <span> \color{lightgray} \dotfill </span> 2018

  - LGBTQ Ally 2.0 (OU) <span> \color{lightgray} \dotfill </span> 2018



## Supervisory Experience

- *Ahmed Sharaf (undergraduate)* <span> \color{lightgray} \dotfill </span> 2022-2023

::: {.content-hidden}

  \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   August 2022-August 2023Undergraduate student web developer. Mentored in professional skills like note taking, working with consultants, writing short project updates, creating and implementing project milestones, collaborative use of GitHub. Graduated December 2023.

:::

- *Henry Dang (undergraduate) * <span> \color{lightgray} \dotfill </span> 2018


::: {.content-hidden}

  \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Undergraduate student cleaning and merging multiple database versions. Mentored in R and version control from complete novice to being able to create a package to calculate triangulation points for radio-tracked telemetry data.

:::

- *Seasonal field technicians (3)* <span> \color{lightgray} \dotfill </span> 2015


::: {.content-hidden}

  \hangindent=0.5em \hangafter=1 \bullet \nobreakspace   Trained seasonal technicians to band, color-band, and relocate birds for behavioral experiments, perform behavioral experiments, and cross-train with coordinating field teams for bird surveys.

:::



# Research and Creative Activities

## Peer-Reviewed Publications

::: {#refs-peer}
:::

## Non-Peer-Reviewed Publications

::: {#refs-reports}
:::

## Conference Presentations

::: {#refs-conference}
:::


## Seminars and Invited Lectures

::: {#refs-invited}
:::


## Popular Articles

Monthly “Birds and Beyond” column for a small Texas newspaper, the Wise County Messenger <span> \color{lightgray} \dotfill </span> 2002-2013

::: {.content-hidden}

- \bullet \nobreakspace September 2002-September 2007, volunteer columnist

- \bullet \nobreakspace November 2007-October 2013, paid columnist

- \bullet \nobreakspace Articles generally focused on natural history and identification of north-central Texas birds, butterflies, plants, and other organisms and descriptions of trips in other areas of Texas and Oklahoma.

:::

::: {#refs-popular}
:::

## Public Talks

::: {#refs-public_talks}
:::



::: {.content-hidden}

Have co-presented talks about birds and ecology <span> \color{lightgray} \dotfill </span> 2001-2007

- \bullet \nobreakspace Denton County Master Gardeners (TX)

- \bullet \nobreakspace Elm Fork Chapter of Texas Master Naturalists

- \bullet \nobreakspace Decatur Lions’ Club

- \bullet \nobreakspace Tallgrass Prairie Audubon Society

- \bullet \nobreakspace Girl Scouts

- \bullet \nobreakspace Boy Scouts

- \bullet \nobreakspace elementary school students in Decatur, TX

- \bullet \nobreakspace 2001, 2006, and 2007 JAKES (Juniors Acquiring Knowledge, Ethics, and Sportsmanship) events (U.S. Forest Service; Texas Parks and Wildlife) at the Lyndon B. Johnson National Grasslands.

:::


# Awards, Honors, and Fellowships

*Thomas & Catherine Luccock Library Award of Excellence* <span> \color{lightgray} \dotfill </span> May 2022

::: {.content-hidden}


-   University of Oklahoma Libraries “The Thomas & Catherine Luccock Library Award of Excellence is the highest honor awarded by the University of Oklahoma Libraries. This prestigious award will be presented annually to recognize and commend an individual for superior performance and contributions to the University of Oklahoma Libraries.”

:::

*Hidden Hero Award University of Oklahoma Libraries* <span> \color{lightgray} \dotfill </span> September 2021

::: {.content-hidden}


-   “Going above and beyond in the performance of your job duties.”

:::


*Collaborative Spirit Award (for STEM Services team) University of Oklahoma Libraries* <span> \color{lightgray} \dotfill </span> April 2020

::: {.content-hidden}


-   “Recognizes a work team or volunteer group that successfully works together to create a product or result that was strengthened by the effort of the team."

:::


*Elective Member American Ornithology Society* <span> \color{lightgray} \dotfill </span> August 2017

::: {.content-hidden}


-   Elected to honorary membership category recognizing contributions to ornithology.

:::


*GAANN (Graduate Assistance in Areas of National Need) Fellow* <span> \color{lightgray} \dotfill </span> August 2012-March 2014



::: {.content-hidden}
*Department of Education*

-   Nominated by department; covers stipend, tuition, fees

:::


*Alumni Fellow, University of Oklahoma Graduate College* <span> \color{lightgray} \dotfill </span> 2008-2014

::: {.content-hidden}


-   “emphasizes the recruitment and retention of outstanding graduate students”.

:::


*OU Biology Department Award for Excellence in Graduate Student Teaching* <span> \color{lightgray} \dotfill </span> May 2013

::: {.content-hidden}


-   University of Oklahoma Department of Biology Nominated for teaching Ecology and Entomology Labs.

:::


*Best oral presentation by a graduate student, Oklahoma Ornithological Society Technical Meeting* <span> \color{lightgray} \dotfill </span> October 2012

::: {.content-hidden}


-   Oklahoma Ornithological Society Fall 2012 technical meeting

:::


*President’s List, University of North Texas* <span> \color{lightgray} \dotfill </span> spring 2005-fall 2007

::: {.content-hidden}


-   For 4.00 GPA while completing at least 12 credit hours in a semester

:::


*National Grasslands Prairie Partner Award* <span> \color{lightgray} \dotfill </span> 2003


::: {.content-hidden}


-   National Grasslands Council For volunteer work at the Lyndon B. Johnson National Grasslands (shared with Mary Curry).

:::


# Service

## Peer Review

Publons profile: [https://publons.com/a/1187905/](https://publons.com/a/1187905/)

-   Auk: Ornithological Advances
-   Avian Conservation and Ecology
-   Condor (now Ornithological Applications)
-   Diversity and Distributions
-   Ecology and Evolution
-   Environmental Pollution
-   Evidence-based Toxicology
-   Ibis
-   Journal of Applied Ecology
-   Northeastern Naturalist
-   Rangeland Ecology and Management
-   Wilson Journal of Ornithology

## Departmental

- *Research Workshops Committee (chair) for University Libraries* <span> \color{lightgray} \dotfill </span> 2021-present

  - Documentation of procedures for committee and workshop organization
  
  - Coordination with Marketing and Communication to ensure timely and consistent outreach
  
  - Standardization of accessibility notices to include default captioning, modality, and logistics

  - Automation of reminder and registration emails via Zapier and Trello

::: {.content-hidden}

- \cdot \nobreakspace  Created cross-training document to find substitute instructors, helpers, and understand organizational needs for software instructors
  
- \cdot \nobreakspace  Created RACI chart for team to understand who to contact during cancellations or rescheduling

:::

- *Hiring committee (chair) for University Libraries*

  - Search: STEM Instruction Librarian <span> \color{lightgray} \dotfill </span>  2024
  
- *Hiring committee (member) for University Libraries*

  - Search: National Weather Center Branch Library Manager <span> \color{lightgray} \dotfill </span>  2023

  - Search: Liaison Coordinator <span> \color{lightgray} \dotfill </span> 2023

  - Search: Liaison Coordinator <span> \color{lightgray} \dotfill </span> 2022

  - Search: Director of Library Marketing & Communications <span> \color{lightgray} \dotfill </span> 2021


- *Graduate Research Retreat Planning Committee (member)* <span> \color{lightgray} \dotfill </span>  2023

- *OU Libraries Awards Committee (member)*  <span> \color{lightgray} \dotfill </span> 2023

- *New employee mentoring program for two new staff*  <span> \color{lightgray} \dotfill </span> 2021-2022

- *Successful proposal for new name tag design* <span> \color{lightgray} \dotfill </span> 2021
  
  - Added option for pronouns to official OU Libraries faculty/staff name badges
  
  - Requested comments and guidance from LGBTQIA+ colleagues

- *OU Libraries Strategic Planning Team 3b (member)* <span> \color{lightgray} \dotfill </span>  2021

- *OU Department of Biology Graduate Selections Committee (graduate student member)* <span> \color{lightgray} \dotfill </span> 2010-2013

- *Founded and organizeed OU Ecology Journal Club* <span> \color{lightgray} \dotfill </span> 2011-2013

::: {.content-hidden}

with weekly discussions by students and faculty of published papers (fall 2011-fall 2013; responsibilities passed to a new student during my last semester of spring 2014 and meetings continued through 2018).

:::

## University

- *Institutional Animal Care and Use Committee (scientist member)*  <span> \color{lightgray} \dotfill </span>February 2021-present

- *OU Coding Outreach for Data Education (CODE) Workshop (helper)* <span> \color{lightgray} \dotfill </span>fall semesters, 2020-2022

- *OU Honors College Undergraduate Research Day (judge)* <span> \color{lightgray} \dotfill </span>April 2020

- *OU Honors College Undergraduate Research Day (judge)*  <span> \color{lightgray} \dotfill </span>April 2019

- *OU School of Architecture Program for Research Enhancement (lay reviewer)* <span> \color{lightgray} \dotfill </span> fall 2018, spring 2019, fall 2019

- *Earth Observation Science for Society and Sustainability (EOS 3) (graduate certificate class, OU)* <span> \color{lightgray} \dotfill </span> August 28, 2017

  - Panelist on “Building a better Ph.D. or M.S.”
  
  ::: {.content-hidden}
  
  - Class taught by Drs. Jeff Kelly, Andrea Contina, and Sara Mata, University of Oklahoma, Norman, OK, USA. 

  ::: 
  
- *OU Graduate College Academic Appeals and Misconduct student panelist* <span> \color{lightgray} \dotfill </span> 2011-2012 academic year

  - Nominated to serve by department



::: {.content-hidden}


nominated by the OU Department of Zoology’s Graduate Liaison for being “an experienced Graduate Student and hav\[ing\] demonstrated the qualities necessary to serve as an Appeals or Misconduct panelist such as judgment, discretion and commitment.”

:::

## External

- *Instructor on TAGS (Geolocator Data Cleaning website) at Geolocation Workshop* <span> \color{lightgray} \dotfill </span> 2018
  
  - Preceding International Ornithological Congress: Vancouver, BC, Canada
  
  ::: {.content-hidden}
  
  August 18-19
  
  :::
  

- *Session Chair*
  
  - “Evolution”, American Ornithology Conference: Tuscon, AZ, USA <span> \color{lightgray} \dotfill </span>  2018
  
  - “Landscape ecology”, American Ornithology Conference: East Lansing, MI, USA <span> \color{lightgray} \dotfill </span> 2017
  
  - “Diseases/parasites”, NAOC-V meeting: Vancouver, BC, Canada <span> \color{lightgray} \dotfill </span> 2012

  - “Diversification- Birds”, Evolution 2011: Norman OK, UISA <span> \color{lightgray} \dotfill </span> 2011

- *Judge*
  
  - Student oral presentations and posters 
    
    - \cdot \nobreakspace American Ornithology Conference: Tuscon, AZ, USA <span> \color{lightgray} \dotfill </span>  2018
    
    - \cdot \nobreakspace American Ornithology Conference: East Lansing, MI, USA  <span> \color{lightgray} \dotfill </span>  2017
    
    - \cdot \nobreakspace North American Ornithological Conference: Washington, DC., USA <span> \color{lightgray} \dotfill </span> 2016
    
- *Cooper Ornithological Society's Early Career Editorial Board*

  - Member <span> \color{lightgray} \dotfill </span>  2011-2012
  
  
::: {.content-hidden}

- *Volunteer, Evolution 2011 meeting, <span> \color{lightgray} \dotfill </span> 17-21 July, Norman OK; driving van.

:::


## Community

- *Nature Walks*

  - National Trails Day at Fort Richardson State Park, TX, co-lead with park manager <span> \color{lightgray} \dotfill </span>  2012
  
  ::: {.content-hidden}
  
  June 2012
  
  :::
  
  - Bird walk for Fort Griffin State Historic Site, TX, lead <span> \color{lightgray} \dotfill </span> 2011
  
  ::: {.content-hidden}
  
  June 2011
  
  :::
  
  - Monthly field trips to LBJ National Grasslands, co-lead <span> \color{lightgray} \dotfill </span>  2004-2005
  
  ::: {.content-hidden}
  
  February 2004 to January 2005
  
  :::
  

- *Volunteer Work*
  
  - Served as an Oklahoma BioBlitz expert biologist <span> \color{lightgray} \dotfill </span> 2011
  
  ::: {.content-hidden}

  at 2011 BioBlitz Oklahoma at Chickasaw National Recreation Area, Murray County, OK
  

  - Compiled checklists of Wise County (TX) birds and butterflies for distribution at the U.S. Forest Service office in Decatur, TX.

  :::
  
  - Participated in Wise County Christmas Bird Count circle <span> \color{lightgray} \dotfill </span>  2000-2007

  - Surveyed for Project Prairie Birds (Texas Parks & Wildlife Department)  <span> \color{lightgray} \dotfill </span> 2002-2006

  ::: {.content-hidden}
  
  in winters of 2002-2006 on the Lyndon B. Johnson National Grasslands

  :::
  
  - Co-edited Tall Grass Tales, newsletter of Tallgrass Prairie Audubon Society <span> \color{lightgray} \dotfill </span> 2001-2004
  
  ::: {.content-hidden}
  
  from December 2001 to October 2004. 
  
  - Assisted in preparing bird specimens and mounts for display at the U.S. Forest Service office in Decatur, TX
  
  :::
  
  - Certified Texas Master Naturalist (Elm Fork Chapter) <span> \color{lightgray} \dotfill </span> 2000-2006
  

    
    ::: {.content-hidden}
    
    - \cdot \nobreakspace Class of 2000,     Completed volunteer hours and advanced training hours for Elm Fork chapter
    
    
    - \cdot \nobreakspace Ended service to focus on undergraduate degree.
    
    :::

# Funding

## Extramural

*Research*

-   *Prairie Biotic Research, Inc. small grants program*
    -   \$1500 <span> \color{lightgray} \dotfill </span> March 2018
    -   Proposal: “An Illustrated Checklist of the Lichens of Wise County, Texas, and Surrounding Areas”
    -   Co-PI Mary Curry
-   *Amazon Web Services (AWS) Cloud Credits for Research program*
    -   \$6500 in computing credits on AWS <span> \color{lightgray} \dotfill </span> 2017
    -   Proposal: “Predictive accuracy and efficiency of spatially explicit species distribution models”
-   *Sigma Xi Grant-in-Aid of Research*
    -   \$500 <span> \color{lightgray} \dotfill </span> spring 2012
    -   Proposal: “Evolution of reproductive isolation in a spatially and temporally complex songbird hybrid zone”
    
    ::: {.content-hidden}
    
    travel mileage to field sites

    :::
    
    
-   *American Museum of Natural History Frank M. Chapman Memorial Fund Grant*
    -   \$2000 <span> \color{lightgray} \dotfill </span> 2012-2013
    -   Proposal: “Shadow of a doubt: species recognition in a complex avian hybrid zone”
    
    ::: {.content-hidden}
    
    research expenses and genetic analysis costs

    :::

-   *American Museum of Natural History Frank M. Chapman Memorial Fund Grant*
    -   \$2000 <span> \color{lightgray} \dotfill </span> 2011-2013
    -   Proposal: “Why songs change over space and time in a complex avian hybrid zone”
    
    ::: {.content-hidden}
    
    research expenses and genetic analysis costs
    
    :::

-   *Oklahoma Ornithological Society*
    -   \$500 <span> \color{lightgray} \dotfill </span> 2012
    -   Proposal: “Shadow of a doubt: species recognition and fitness in a complex avian hybrid zone”
    
-   *Oklahoma Ornithological Society*
    -   \$400 <span> \color{lightgray} \dotfill </span> 2010
    -   Proposal: “Genetic and vocal dynamics of a complex avian hybrid zone”


*Travel Awards*

-   *American Ornithological Society Post-Doctoral Travel Award*
    -   \$290 <span> \color{lightgray} \dotfill </span> August 2017
    

::: {.content-hidden}


    -   To attend 2017 American Ornithology Conference in East Lansing, MI

:::

-   *Association of Field Ornithologists’ Post-Doctoral Travel Award*
    -   \$260 <span> \color{lightgray} \dotfill </span> August 2016

::: {.content-hidden}

    -   To attend NAOC2016 meeting in Washington, DC

:::

-   *American Ornithologists Union/Cooper Ornithological Society/Society of Canadian Ornithologists Joint Student Travel Award*
    -   \$370 <span> \color{lightgray} \dotfill </span> September 2014

::: {.content-hidden}

    -   To attend AOU/COS/SCO joint meeting in Estes Park, CO

:::

-   *American Ornithologists Union/Cooper Ornithological Society Student Travel Award*
    -   \$333 <span> \color{lightgray} \dotfill </span> August 2013

::: {.content-hidden}

    -   To attend AOU/COS joint meeting in Chicago, IL

:::

-   *American Society of Naturalists Student Travel Award*
    -   \$500 <span> \color{lightgray} \dotfill </span> June 2013

::: {.content-hidden}

    -   To attend Evolution 2013 meeting in Snowbird, UT

:::

-   *Student Travel Award from 2012 North American Ornithological Conference*
    -   \$300 <span> \color{lightgray} \dotfill </span> 2012

::: {.content-hidden}

    -   To attend 2012 North American Ornithological Conference in Vancouver, BC

:::



## Intramural

*Research and Projects*

-   *OU Data Institute for Societal Challenges Seed Funding*
    -   \$10,000 <span> \color{lightgray} \dotfill </span> June 2022-August 2023
    -   Seed funding to develop Statistics Helper educational website prototype
-   *M. Blanche Adams and M. Frances Adams Memorial Scholarships in Zoology: Summer Research Scholarship*
    -   \$2500 <span> \color{lightgray} \dotfill </span> summer 2012
    -   Proposal: “Evolution of reproductive isolation in a spatially and temporally complex songbird hybrid zone”
-   *George Miksch Sutton Scholarship in Ornithology*
    -   \$3500 <span> \color{lightgray} \dotfill </span> 2012
    -   Proposal: “Testing hybrid zone models using the Tufted (*Baeolophus bicolor*) and Black-crested (*B. atricristatus*) Titmouse hybrid zone”

    ::: {.content-hidden}

    research equipment, travel, and lab expenses

    :::

-   *M. Blanche Adams and M. Frances Adams Memorial Scholarships in Zoology: Academic Year Scholarship*
    -   \$1000 <span> \color{lightgray} \dotfill </span> 2011-2012
    -   Proposal: “Behavioral and genetic dynamics of a complex avian hybrid zone”
    
    ::: {.content-hidden}
    
    -   for professional travel and research expenses

    :::

-   *M. Blanche Adams and M. Frances Adams Memorial Scholarships in Zoology: Summer Research Scholarship*
    -   \$2500 <span> \color{lightgray} \dotfill </span> summer 2011
    -   Proposal: “Behavioral and genetic dynamics of a complex avian hybrid zone”
-   *George Miksch Sutton Scholarship in Ornithology*
    -   \$6700 <span> \color{lightgray} \dotfill </span> 2011
    -   Proposal: “Testing hybrid zone models using the Tufted (*Baeolophus bicolor*) and Black-crested (*B. atricristatus*) Titmouse hybrid zone”
    
    ::: {.content-hidden}
  
    research equipment, travel, and lab expenses

    :::
    

-   *M. Blanche Adams and M. Frances Adams Memorial Scholarships in Zoology: Academic Year Scholarship*
    -   \$1000 <span> \color{lightgray} \dotfill </span> 2010-2011
    -   Proposal: “Behavioral and genetic dynamics of a complex avian hybrid zone”
       
    ::: {.content-hidden}
    
     -   for professional travel and research expenses

    :::
    

-   *M. Blanche Adams and M. Frances Adams Memorial Scholarships in Zoology: Summer Research Scholarship*
    -   \$756 <span> \color{lightgray} \dotfill </span> summer 2010
    -   Proposal: “Behavioral and genetic dynamics of a complex avian hybrid zone”
    
   
    ::: {.content-hidden}
    
     -    partial summer research assistantship in department (complements 2010 Sutton Scholarship stipend, below)

    :::
    

-   *George Miksch Sutton Scholarship in Ornithology*
    -   \$4800 <span> \color{lightgray} \dotfill </span> 2010
    -   Proposal: “Dynamics of a complex avian hybrid zone”   
    
    ::: {.content-hidden}
    
    -   research equipment, travel, lab expenses, and partial summer stipend
    
    :::
    
    
    
-   *OU Graduate Student Senate Research and Creative Endeavors Grant*
    -   \$224.82 <span> \color{lightgray} \dotfill </span> spring 2010
    
       
    ::: {.content-hidden}
  
    -   Research equipment and travel to north-central Texas to examine field sites

    :::
    


-   *OU Robberson Research Grant*
    -   \$1000 (granted once per degree) <span> \color{lightgray} \dotfill </span> February 2010
   
    ::: {.content-hidden}
    
     -   Research travel and genetic analysis costs
     
    :::
    
-   *OU Graduate Student Senate Research and Creative Endeavors Grant*
    -   \$315.62 <span> \color{lightgray} \dotfill </span> fall 2009
    
    ::: {.content-hidden}
    
    -   Travel expenses to southwestern Oklahoma to examine field sites
    
    :::
    
-   *M. Blanche Adams and M. Frances Adams Memorial Scholarships in Zoology: Summer Research Scholarship*
    -   \$2500 <span> \color{lightgray} \dotfill </span> summer 2009
    -   Proposal: “Behavioral and genetic dynamics of a complex avian hybrid zone”; summer research assistantship in department
-   *George Miksch Sutton Scholarship in Ornithology*
    -   \$5000 <span> \color{lightgray} \dotfill </span> 2009
    -   Proposal: “Dynamics of a complex avian hybrid zone”; research equipment and travel expenses

*Travel Awards*

-   *OU College of Arts and Sciences Student Travel Fund*
    -   \$750 <span> \color{lightgray} \dotfill </span> August 2013

::: {.content-hidden}

    -   Travel to joint meeting in Chicago, IL, Utah in August 2013, \$750.

:::

-   *OU Department of Biology Travel Funding*
    -   \$250 <span> \color{lightgray} \dotfill </span> May 2013

::: {.content-hidden}

    -   To attend Evolution 2013 meeting in Snowbird, UT in June 2013

:::

-   *OU College of Arts and Sciences Student Travel Fund*
    -   \$750 <span> \color{lightgray} \dotfill </span> August 2012

::: {.content-hidden}

    -   Travel to North American Ornithological Conference in Vancouver BC in August 2012

:::

-   *OU Department of Zoology travel funding*
    -   \$250 <span> \color{lightgray} \dotfill </span> February 2011

::: {.content-hidden}

    -   Travel to Association of Field Ornithologists/Cooper Ornithological Society/Wilson Ornithological Society joint meeting in Kearney, Nebraska in March 2011

:::

-   *OU College of Arts and Sciences Student Travel Fund*
    -   \$750 <span> \color{lightgray} \dotfill </span> October 2010

::: {.content-hidden}

    -   Travel to Association of Field Ornithologists' conference in Ogden, Utah in August 2010

:::

-   *OU Robberson Travel Grant*
    -   \$500 (granted once per degree) <span> \color{lightgray} \dotfill </span> October 2010

::: {.content-hidden}

    -   Travel to Association of Field Ornithologists' conference in Ogden, Utah in August 2010

:::

-   *OU Graduate Student Senate Conference and Creative Exhibition Grant*
    -   \$79.86 <span> \color{lightgray} \dotfill </span> spring 2010

::: {.content-hidden}

    -   Lodging and daily expenses at Southwestern Association of Naturalists’ meeting in Junction, TX

:::

-   *Carl and Pat Bynum Riggs Scholarship*
    -   \$500 <span> \color{lightgray} \dotfill </span> summer 2009

::: {.content-hidden}

    -   To defray expenses of course tuition and fees for O.U. Biological Station summer session; Molecular Techniques for Field Biology class

:::



# Memberships

*American Statistical Association*

-   Education Section and Oklahoma Chapter <span> \color{lightgray} \dotfill </span> 2022-present

*American Ornithological Society*

-   Elective Member <span> \color{lightgray} \dotfill </span> 2017-present

-   Member <span> \color{lightgray} \dotfill </span> 2010-2016

*Association of Field Ornithologists*

-   Member <span> \color{lightgray} \dotfill </span> 2012-2022

*Research Data Preservation Association*

-   Member <span> \color{lightgray} \dotfill </span> 2018-2019

# References

*Ms. Karie Antell*

- Email: kantell\@ou.edu
- Phone: +1 405-325-4142
- Head of Library Instruction and Liaison Services, University of Oklahoma Libraries
  - 401 W. Brooks St.
  - Norman, OK, 73019, USA

\nobreakspace
*Ms. Sarah Robbins*

- Email: srobbins\@ou.edu
- Phone: +1 405-325-5293
- Senior Director, Strategic & Research Initiatives, University of Oklahoma Libraries
  - 401 W. Brooks St.
  - Norman, OK, 73019, USA
    
\nobreakspace

*Dr. Michael A. Patten*

- Email: michael.a.patten\@nord.no
- Phone: +4774022822 (Norway)
- Professor, Faculty of Biosciences and Aquaculture, Nord University
  - Postboks 1490
  - 8049 Bodø
  - Steinkjer, Norway

\nobreakspace

*Dr. Eli Bridge*

- Email: ebridge\@ou.edu
- Phone: +1 405-325-4034
- Director, Oklahoma Biological Survey, University of Oklahoma
  - 111 E. Chesapeake Street
  - Norman, OK, 73019, USA

\nobreakspace

*Dr. Nicola Koper*

- Email: Nicola.Koper\@unbc.ca
- Phone: +1 250-960-5121
- Dean, Faculty of Environment, University of Northern British Columbia
  - 3333 University Way
  - Prince George, BC, V2N 4Z9, Canada