# Summary {.unnumbered}

I am a research librarian, specializing in STEM and quantitative, with additional experience helping researchers synthesize and analysze data.

## Goals
As a science librarian at OU Libraries in concert with my colleagues in the STEM Services team, I have presented and generated open access content around data analysis, management, and visualization.  We continue to expand these offerings each year.  As current chair of our research workshops committee, I'm leading improvements to our data and research workshop descriptions to improve cross-disciplinary appeal, expand our default accessibility accommodations, and produce content to expand uptake of data and research better practices to make scholars' lives easier and more productive. 

## Background
I use a wide range of software tools to explore interesting research questions from my own areas of expertise (originally in quantitative biology), in collaboration with other researchers, and now helping patrons in my current position as a science librarian. I am experienced in and enjoy helping other researchers use R and SAS, choose appropriate statistical techniques, and manage their data.  This is evidenced by my certification as an instructor for Software and Data Carpentries, co-instructing Quantitative Methods in Natural Resource Management (a graduate-level course on experimental design and statistics) during my time at the Natural Resources Institute, and helping many patrons and collaborators with R, SAS, ArcGIS, QGIS, and statistics.  This is now part of my position as a science librarian to help guide patrons to appropriate software and statistical resources.

In my own research, I have used a wide variety of techniques, from univariate (including basic statistics to mixed models to power analyses) to multivariate (including canonical correlation analysis to PCA to Mantel tests) statistics.  I have also spoken on more than one occasion about data and project management from my experiences managing my own and others' data during my Ph.D. and post-doctoral work and instruct with The Carpentries to promote best practices in data and coding skills for scientists of all disciplines.


