# Teaching Experience

## Research Data Workshops
Teach, develop, and modify curricula to enhance researchers' abilities to process and visualize information.

::: {.column-margin}
2018-present

@sec-science-librarian

:::

- Developed curricula for multiple workshops
  - Smoother Meetings
  - Repetitive Tasks in R
  - ggplot2 in R
  - Troubleshooting Computer Code (collaboration with co-instructor Logan Cox)
  - Concepts of Data-Driven Visualization
- Co-developed curricula for multiple workshops
  - Managing Research Files
  - Citation management with Zotero
  - Open Science Framework intro
- Instructing from existing curricula
  - R for Scientific PRogramming
  - R for Ecology
  - R for Social Sciences
  - R for GIS
    - Including modifications for 2.5 hr two session short version
  - Tidy data/spreadsheets
  - SQL
  - ??
  - Git/GitHub
    - Including modifications for 2.5 hr two session short version
  - Bash
- Helping from existing curricula
  - OpenRefine
  - Python
- Chairing organizational committee since its inception (2022)
  - Repsonsible for reminding instructors of scheduling
  - Automated emails via Zapier and Trello to instructors to remind them and to listserv to announce registration
- Certified Carpentries instructor (as of 2019) as part of Science Librarian position


## Library instruction
Teach, develop, and scaffold information literacy skills to undergraduate and graduate-level STEM students

::: {.column-margin}
2018-present
:::

- Develop and deliver one-shot and multiple visit teaching sessions
- Develop information literacy materials for asynchronous learning
- Using ACRL STEM literacy framework
- Deliver materials in-person, hybrid, and virtual
- Teach solo, with a shadow trainee, and in collaboration (for interdisciplinary courses)
- 20-50 class visits per year teaching information literacy to undergraduate and graduate
classes in STEM fields

## Instructor of record

### Study Design and Quantitative Methods in Natural Resource Management {#sec-nrm-quant}

Cross-listed graduate/undergraduate lab.

::: {.column-margin}
2015-2016 (winter only)
:::

Co-instructor with Dr. Nicola Koper

Presenting R code to implement statistical methods; lecture on multivariate statistics; and grading half of assignments

### Ecological Dimensions of Natural Resource Management
Graduate level lecture class

::: {.column-margin} 
Fall 2015
:::

Sessional instructor: Lecture, guide discussions, grade assignments.


## Mentoring

### University of Manitoba Students

Guidance on project design, sampling, statistical analysis, and use of R and SAS for Master’s (14), undergraduate (1), and Ph.D. (1) students in Nicola Koper lab

::: {.column-margin}
2014-2016
:::

Master’s (2) and Ph.D. (1) students at the Natural Resources Institute and Biology departments.

### University of Oklahoma Undergraduates
#### Alexandra Ainsworth

Independent study (3 credit hours), PI: Michael A. Patten

::: {.column-margin}
Spring 2012
:::

She fed captive birds, assisted with mate choice trial set-up, bird capture, DNA extraction using Qiagen DNeasy kits, PCR, and agarose gel electrophoresis.

#### Sarai H. Stuart

Volunteer, recently graduated from OU.

::: {.column-margin}
January-April 2012, January-March 2013
:::

Volunteer was a recent OU graduate wanting field experience before applying to jobs and/or graduate school. She learned about mist-netting, trapping, banding, setting up mate choice trials, maintaining captive birds, DNA extraction using Qiagen DNeasy kits, PCR, and agarose gel electrophoresis. Graduated with Ph.D. from University of Illinois at Champaign-Urbana.


## Graduate Teaching Assistantships

### Intro. to Evolution, Ecology, and Diversity
Undergraduate, majors lab

::: {.column-margin}
2012 (spring) One semester  
:::

Professor: Dr. Phil Gibson 

Presentation of weekly lab materials, creating and grading quizzes, grading lecture exams, proctoring lecture and lab exams, and guiding students through lab experiments.

### Entomology

Cross-listed undergraduate/graduate lab

::: {.column-margin}
2009-2012 (fall only - total four semesters)
:::

Professor: Dr. Ken Hobson (retired)

Presentation of insect orders and families; creating and grading quizzes and exam; and leading students on field trips

### Introductory Zoology Lab
Undergraduate, non-majors lab

::: {.column-margin}
Fall 2008, fall 2012
::: 

Professor: Dr. Penny Hopkins (retired)

Lecturing on the day’s lab topic, assisting students with dissections, and writing, administering, and grading quizzes

### Principles of Ecology
Undergraduate, majors lab

::: {.column-margin}
2009 (spring & fall), 2010-2011 (fall only) 
:::

Professor: Dr. Ken Hobson (retired)

Discussion of concepts, guiding students through field experiments; and grading lab reports.

## Undergraduate Teaching Assistant (Volunteer)

### Insect Biology Lab
Cross-listed undergraduate/graduate lab

::: {.column-margin}
Fall 2006 and fall 2007
:::

Professor: Dr. James Kennedy

Help students with keying insects, assist students on field trips, and proctor exams and quizzes with the graduate teaching assistants.
