# Awards, Honors, and Fellowships

## Thomas & Catherine Luccock Library Award of Excellence

::: {.column-margin}
May 2022 
:::

University of Oklahoma Libraries “The Thomas & Catherine Luccock Library Award of Excellence is the highest honor awarded by the University of Oklahoma Libraries. This prestigious award will be presented annually to recognize and commend an individual for superior performance and contributions to the University of Oklahoma Libraries.”

## Hidden Hero Award University of Oklahoma Libraries

::: {.column-margin}
September 2021
:::

“Going above and beyond in the performance of your job duties.”

## Collaborative Spirit Award (for STEM Services team) University of Oklahoma Libraries

::: {.column-margin}
April 2020
:::

“Recognizes a work team or volunteer group that successfully works together to create a product or result that was strengthened by the effort of the team."

## Elective Member American Ornithology Society

::: {.column-margin}
August 2017
:::

Elected to honorary membership category recognizing contributions to ornithology.

## GAANN (Graduate Assistance in Areas of National Need) Fellow Department of Education

::: {.column-margin}
August 2012-March 2014 (graduation)
:::


Nominated by department; covers stipend, tuition, fees

## Alumni Fellow University of Oklahoma Graduate College

::: {.column-margin}
2008-2014
:::

“emphasizes the recruitment and retention of outstanding graduate students”. More information at <http://www.ou.edu/gradweb/funding_and_aid/fellowships.html>.

## Biology Department Award for Excellence in Graduate Student Teaching

::: {.column-margin}
May 2013
:::


University of Oklahoma Department of Biology Nominated for teaching Ecology and Entomology Labs.

## Best oral presentation by a graduate student

::: {.column-margin}
October 2012
:::

Oklahoma Ornithological Society Fall 2012 technical meeting

## Spring 2005-Fall 2007 President’s List University of North Texas

::: {.column-margin}

For 4.00 GPA while completing at least 12 credit hours in a semester

## National Grasslands Prairie Partner Award

::: {.column-margin}
2003
:::

(shared with M. Curry) National Grasslands Council For volunteer work at the Lyndon B. Johnson National Grasslands.
