# Service

## Departmental

Hiring committee (chair) for University Libraries STEM Instruction Librarian – 2024 (in progress) Hiring committee for University Libraries National Weather Center Branch Library Manager – 2023 (successful search) UL Awards committee (2023) Hiring committee for University Libraries Liaison Coordinator – 2022-2023 (unsuccessful searches) Hiring committee for University Libraries Marketing & Communication Search – 2021 (successful search) Successful proposal (with assistance from LGBTQIA+ colleagues) to add option for pronouns to official University Libraries name badges for faculty/staff - 2021 Department of Biology Graduate Selections Committee graduate student representative (2010-2013 academic years); provide comments on new graduate student applications to the department. Founded and organize Ecology Journal Club at OU with weekly discussions by students and faculty of published papers (fall 2011-fall 2013; responsibilities passed to a new student during my last semester of spring 2014 and meetings continue each semester).

## University

Institutional Animal Care and Use Committee Scientist Member, February 2021-present. OU Coding Outreach for Data Education (CODE) Workshop helper for R and Python: Fall 2020, Fall 2021, Fall 2022. Judge for OU Honors College Undergraduate Research Day, April 2020. Judge for OU Honors College Undergraduate Research Day, April 2019. Reviewer for OU School of Architecture Program for Research Enhancement to provide layperson’s feedback: fall 2018, spring 2019, fall 2019. Software and Data Carpentry helper and instructor: 2017-present. Guest panelist in Earth Observation Science for Society and Sustainability (EOS 3) interdisciplinary certificate program class on “Building a better Ph.D. or M.S.” August 28, 2017. Class taught by Drs. Jeff Kelly, Andrea Contina, and Sara Mata, University of Oklahoma, Norman, OK, USA. Nominated to serve as a OU Graduate College Academic Appeals and Misconduct student panelist (2011-2012 academic year); nominated by the OU Department of Zoology’s Graduate Liaison for being “an experienced Graduate Student and hav\[ing\] demonstrated the qualities necessary to serve as an Appeals or Misconduct panelist such as judgment, discretion and commitment.”

## Peer review
Publons profile: publons.com/a/1187905/

- Auk: Ornithological Advances
- Avian Conservation and Ecology 
- Condor (now Ornithological Applications)
  - Member of the Cooper Ornithological Society's Early Career Editorial Board for Condor (2011-2012; graduated from the board at the end of that period).
- Diversity and Distributions
- Ecology and Evolution 
- Environmental Pollution 
- Evidence-based Toxicology 
- Ibis 
- Journal of Applied Ecology 
- Northeastern Naturalist 
- Rangeland Ecology and Management 
- Wilson Journal of Ornithology

## External
- Instructor on TAGS (Geolocator Data Cleaning website) at Geolocation Workshop August 18-19, 2018. Preceding International Ornithological Congress: Vancouver, BC, Canada. 
- Session Chair (“Evolution”), 2018 American Ornithology Conference: Tuscon, AZ, USA.
- Judged student presentations (oral presentations and posters) at 2018 American Ornithology Conference: Tuscon, AZ, USA.
- Session Chair (“Landscape ecology”), 2017 American Ornithology Conference: East Lansing, MI, USA. 
- Judged student presentations (oral presentations and posters) at 2017 American Ornithology Conference: East Lansing, MI, USA. 
- Judged undergraduate presentations (oral presentations and posters) at North American Ornithological Conference 2016: Washington, DC., USA. 
- Presented and led discussion on project and risk management during Critical Skills for the Early Career Professional workshop at 2015 The Wildlife Society Meeting, Winnipeg, MB, October 2015. 
- Panelist on careers in biology at Prairie University Biology Symposium, Winnipeg, MB, February 2015; one of three early career biologists answering questions from graduate students. 
- Undergraduate Diversity Mentor for two undergraduates attending the Evolution 2013 meeting in Snowbird, UT. 
- Session Chair (“Diseases/parasites”), NAOC-V meeting, 14-18 August 2012, Vancouver BC. 
- Volunteer, Evolution 2011 meeting, 17-21 July, Norman OK; driving van. 
- Session Chair (“Diversification- Birds”), Evolution 2011 meeting, 17-21 July 2011, Norman OK. 

## Community
- Co-led nature walk for National Trails Day at Fort Richardson State Park, TX, with park manager in June 2012.
- Expert biologist at 2011 BioBlitz Oklahoma at Chickasaw National Recreation Area, Murray County, Oklahoma. Guided bird walk for Fort Griffin State Historic Site, TX, June 2011.
- Co-led monthly field trips to the Lyndon B. Johnson National Grasslands from February 2004 to January 2005. 
- Compiled checklists of Wise County birds and butterflies for distribution at the U.S. Forest Service office in Decatur. 
- Participated in Wise County Christmas Bird Count circle from 2000-2007. 
- Participated in Project Prairie Birds in winters of 2002-2006 on the Lyndon B. Johnson National Grasslands. 
- Co-editor of Tall Grass Tales, newsletter of Tallgrass Prairie Audubon Society, from December 2001 to October 2004.
- Assisted in preparing bird specimens and mounts for display at the U.S. Forest Service office in Decatur, TX. 
- Completed volunteer hours and advanced training hours for Elm Fork chapter of Texas Master Naturalist program, Class of 2000. Certified from 2000 to 2006. 