# Positions Held

## Science Librarian {#sec-science-librarian}

University Libraries, University of Oklahoma (Norman, OK, USA)

::: column-margin
2018-present
:::

Supervisor: Karie Antell

### Supervisory experience

-   Ahmed Sharaf (August 2022-August 2023): Undergraduate student web developer. professional skills like note taking, working with consultants, writing short project updates, creating and implementing project milestones, collaborative use of GitHub. Graduated December 2023.

## Post-doctoral research associate

Oklahoma Biological Survey, University of Oklahoma (Norman, OK, USA)

::: column-margin
2016-2018
:::

PI: Dr. Eli S. Bridge

PI: Dr. Michael A. Patten (2018)

### Supervisory experience

-   Henry Dang (2017-2018?)

## Research Associate

Natural Resources Institute, University of Manitoba (Winnipeg, MB, Canada)

::: column-margin
2016
:::

PI: Dr. Nicola Koper

## Post-doctoral Fellow

Natural Resources Institute, University of Manitoba, (Winnipeg, MB, Canada)

::: column-margin
2014-2016
:::

PI: Dr. Nicola Koper

## Supervisory experience

-   3 Field technicians summer 2015

## U.S. Forest Service Contractor

Caddo/Lyndon B. Johnson National Grasslands, US Forest Service (Decatur, TX, USA)

::: column-margin
March-June 2008
:::

Supervisor: Alfredo Sanchez, USFS Wildlife Biologist (retired)

Conducted a Black-capped Vireo survey and designed a Loggerhead Shrike survey on LBJ National Grasslands.

## Undergraduate research assistant

Aquatic Ecology Lab, University of North Texas (Denton, TX, USA)

::: column-margin
March-August 2007
:::

PI: Dr. James Kennedy

Sorted aquatic invertebrates in sediment samples, identified Chironomidae subfamilies and formatted data

## Seasonal Field Biologist

Leon River Restoration Project (with Texas A&M University)

::: column-margin
May-July 2006
:::

Field site: private properties near Gatesville, TX

Point counts of birds, nest searching, fledgling searching, and entering data for one field season.

## Undergraduate research assistant

Aquatic Ecology Lab, University of North Texas (Denton, TX, USA)

::: column-margin
October 2005-May 2006
:::

PI: Dr. James Kennedy

Sorted aquatic invertebrates in sediment samples part-time.

## Field technician

Texas Agricultural Experiment Station in Vernon, TX

::: column-margin
June-August 2005
:::

Counting birds, nest searching, measuring vegetation, and sampling insects for one field season.

## U.S. Forest Service Contractor

Caddo/Lyndon B. Johnson National Grasslands, US Forest Service (Decatur, TX, USA)

::: column-margin
December 2001-February 2002
:::

Counting grassland bird species along designated transects on the Lyndon B. Johnson National Grasslands.

```{r}
#| echo: false
#| warning: false
#| output: asis
# class-output: "sourceCode r"

# cat(readLines("section-work_positions.qmd"), sep = "\n")

```
