# Publications

## Peer-reviewed {#sec-peer}

[@semenovGeographicallyConsistentHybridization2023]

[@robbinsRecruitingHiringOnBoarding2022]

[@rockwoodDistributedExpertiseLeadership2022]

[@pattenForgingBayesianLink2021]

[@gaffinArachnidNavigationReview2020]

[@curryComplexSpatiotemporalVariation2019]

[@warringtonNoiseFourTypes2018]

[@curryNoiseSourceIndividual2018]

[@curryVaryingDatasetResolution2018]

[@curryAbilityAlterSong2017]

[@pipherCattleGrazingIntensity2016]

[@curryShadowDoubtPremating2016]

[@koperEffectsAmbientNoise2016]

[@curryIntegratedFrameworkHybrid2015]

[@curryCurrentHistoricalExtent2014]

[@bridgeEffectsNutritionalCondition2010]

[@curryFactorsAffectingInteraction2010]

## Non-Peer Reviewed Talks

### Presentations and Posters

-   Indicates presenter

### Invited Lectures and Seminars

-   Indicates presenter

## Impact

## Outreach

Curry, C.M.\* 14 Feb. 2019. Can they hear each other now? Noise and its effects on birds in the Canadian prairies and elsewhere. Fort Worth Audubon Society: Fort Worth, TX. (Public talk). Curry, C.M.\* 22 Jan. 2018. Can they hear each other now? Noise and its effects on birds in the Canadian prairies and elsewhere. Oklahoma City Audubon Society: Oklahoma City, OK. (Public talk). Curry, C.M.\* 2015. Evolution in action in Oklahoma and Texas. Presentations via teleconference to high school students in Jenks, Oklahoma AP Environmental Science classes (four periods, Mr. Bryan Yockers) about the evolution of reproductive isolation in titmice. Curry, C.M.\* 2012. Titmice in Oklahoma and Texas: what makes a hybrid zone? Oklahoma City Audubon Society: Oklahoma City, OK. (Public talk). Co-led nature walk for National Trails Day at Fort Richardson State Park, TX, with park manager in June 2012. Expert biologist at 2011 BioBlitz Oklahoma at Chickasaw National Recreation Area, Murray County, Oklahoma. Guided bird walk for Fort Griffin State Historic Site, TX, June 2011. Curry, C.M.\* 2009. Hybrid zones: titmice and the nature of species. Darwin-a-thon public education event at University of Oklahoma: Norman, OK. (Public talk). Assisted in preparing bird specimens and mounts for display at the U.S. Forest Service office in Decatur, TX. Completed volunteer hours and advanced training hours for Elm Fork chapter of Texas Master Naturalist program, Class of 2000. Certified from 2000 to 2006. Have co-presented talks about birds and ecology to Denton County Master Gardeners (TX), Elm Fork Chapter of Texas Master Naturalists, Decatur Lions’ Club, Tallgrass Prairie Audubon Society, Girl Scouts, Boy Scouts, elementary school students in Decatur, TX, and 2001, 2006, and 2007 JAKES (Juniors Acquiring Knowledge, Ethics, and Sportsmanship) events (U.S. Forest Service; Texas Parks and Wildlife) at the Lyndon B. Johnson National Grasslands. Co-led monthly field trips to the Lyndon B. Johnson National Grasslands from February 2004 to January 2005. Compiled checklists of Wise County birds and butterflies for distribution at the U.S. Forest Service office in Decatur. Participated in Wise County Christmas Bird Count circle from 2000-2007. Participated in Project Prairie Birds in winters of 2002-2006 on the Lyndon B. Johnson National Grasslands. Co-editor of Tall Grass Tales, newsletter of Tallgrass Prairie Audubon Society, from December 2001 to October 2004.

## Popular

Popular articles: Monthly “Birds and Beyond” column for a small Texas newspaper, the Wise County Messenger. September 2002-September 2007, volunteer columnist; November 2007-October 2013, paid columnist. Articles generally focused on natural history and identification of north-central Texas birds, butterflies, plants, and other organisms and descriptions of trips in other areas of Texas and Oklahoma. Curry, Claire. 2004. West Nile virus: birds, people, and Texas.” Texas Birds 5(1):14-16. -A short review of West Nile Virus after its initial outbreak. Curry, Claire. 2004. Killer meadowlarks. Texas Birds 5(1):29-30. -Observations on an Eastern Meadowlark killing American Goldfinches during a winter storm. Curry, Claire. 2004. Flight path: Young Birder of the Year contest \~ A birding essay: Stubs. Birding August 36(4):354-356. -Observations on a female Archilochus sp. hummingbird with a broken beak. Curry, Claire. 2004. Real birders drool. IN Claire Curry, Robert M. Milardo, and Richard Frechette. 2004. Dimensions: Three flights of fancy. Birding 36(3):288-289. -Humorous essay on the canine birding experience. Curry, Claire. 2002. The tail of an unfortunate chickadee. Winging It 14(2):4. -Description of a Carolina Chickadee trapped in an Argiope sp. spider web.
