# Positions Held

## Science Librarian {#sec-science-librarian}

University Libraries, University of Oklahoma (Norman, OK, USA)

::: column-margin
2018-present
:::

### Supervisors
- Karie Antell (2024-present)
- Sarah Robbins (2018-2024)

### Supervisory experience

-   Ahmed Sharaf (August 2022-August 2023): Undergraduate student web developer. professional skills like note taking, working with consultants, writing short project updates, creating and implementing project milestones, collaborative use of GitHub. Graduated December 2023.

## Post-doctoral research associate

Oklahoma Biological Survey, University of Oklahoma (Norman, OK, USA)

::: column-margin
2016-2018
:::

### Supervisors
- PI: Dr. Eli S. Bridge
- PI: Dr. Michael A. Patten (2018)

### Supervisory experience
-   Henry Dang (undergraduate research assistant)

## Research Associate

Natural Resources Institute, University of Manitoba (Winnipeg, MB, Canada)

::: column-margin
2016
:::

### Supervisor
- PI: Dr. Nicola Koper

Promotion from previous position as Post-doctoral Fellow.

## Post-doctoral Fellow

Natural Resources Institute, University of Manitoba, (Winnipeg, MB, Canada)

::: column-margin
2014-2016
:::

### Supervisor
- PI: Dr. Nicola Koper

### Supervisory experience

-   Managed three field technicians (summer 2015)

## U.S. Forest Service Contractor

Caddo/Lyndon B. Johnson National Grasslands, US Forest Service (Decatur, TX, USA)

::: column-margin
March-June 2008
:::

### Supervisor
- Alfredo Sanchez, USFS Wildlife Biologist (retired)

Conducted a Black-capped Vireo survey and designed a Loggerhead Shrike survey on LBJ National Grasslands.

## Undergraduate research assistant

Aquatic Ecology Lab, University of North Texas (Denton, TX, USA)

::: column-margin
March-August 2007
:::

### Supervisor
- PI: Dr. James Kennedy

Sorted aquatic invertebrates in sediment samples, identified Chironomidae subfamilies and formatted data

## Seasonal Field Biologist

Leon River Restoration Project (with Texas A&M University)

::: column-margin
May-July 2006
:::

### Supervisors
- Andy Campomizzi
- Shannon Farrell

Field site: private properties near Gatesville, TX

Point counts of birds, nest searching, fledgling searching, and entering data for one field season.

## Undergraduate research assistant

Aquatic Ecology Lab, University of North Texas (Denton, TX, USA)

::: column-margin
October 2005-May 2006
:::

### Supervisor
- PI: Dr. James Kennedy

Sorted aquatic invertebrates in sediment samples part-time.

## Field technician

Texas Agricultural Experiment Station in Vernon, TX

::: column-margin
June-August 2005
:::

### Supervisor
- PI: Dr. Dean Ransom

Counting birds, nest searching, measuring vegetation, and sampling insects for one field season.

## U.S. Forest Service Contractor

Caddo/Lyndon B. Johnson National Grasslands, US Forest Service (Decatur, TX, USA)

::: column-margin
December 2001-February 2002
:::

Counting grassland bird species along designated transects on the Lyndon B. Johnson National Grasslands.
