# Training and Skills

## Skills

### Evidence synthesis
- Evidence Synthesis Institute. Using training to assist OU community members from departments of Social Work, Mathematics, Health and Exercise Science, Geography & Environmental Sustainability, Education

::: {.column-margin}
August 2022 cohort
:::

- [Development of Evidence Synthesis LibGuide Page (external link)](https://guides.ou.edu/data_resources/synthesis) for initial information for community members:  Collaborating with Writing Center on a future questionnaire to guide users to specific types of synthesis.
- Two peer-reviewed narrative reviews (@sec-peer)

### Certified Carpentries instructor

Have taught modules on Git/GitHub, Bash, OpenRefine, Tidy Data, R (both Software and Data Carpentry versions), and helped with Python

### Working with People and Organizations
- Consultations for undergraduates, graduate students, post-doctoral researchers, staff, faculty, and community members
- Collaborating with partner organizations and co-workers 
- Maintaining good relationships for permission for field work on private (US and Canada), state (US), and federal (US) land
- Obtaining permission for field work on private (US), state (US), and federal (US) land
- Permitting for avian research at university, state, provincial, and federal (US and Canada) levels

### Statistical Advising
- Univariate statistics
  - Generalized linear models (GLM, ANOVA, ANCOVA)
  - Mixed model/hierarchical generalized linear models
- Multivariate statistics
  - Decision trees
  - Random forest
  - Principal components analysis (PCA) and choice of ordination techniques
  - Canonical correlation analysis
  - Profile analysis

## Software

### Statistical Programs
- R 4.0+
- SAS 9.2+
- SPSS

### Geographic Information Systems (GIS)
- R for GIS: packages ‘rgdal’, ‘sp’, ‘sf’, ‘terra’, ‘raster’, and ‘rgeos’
- QuantumGIS opensource GIS software v. 2.10+
- ESRI ArcGIS 9.2 and later
  - Good relationship with vendor representatives at OU.
  - Current use for consultations
  - Past use for research
  - Assisting users with migration to ArcGIS Pro from ArcMap
  - Completed course Introduction to Geographic Information Systems course (UNT, Fall 2007)

### Graphics and Data Visualization
- R package `ggplot2` and extensions such as `ggparty`
- RShiny
- Inkscape 0.48+ (creating vector graphics)

### Data management and processing

#### Data wrangling
- R package 'tidyverse'
- R package 'sqldf'
- OpenRefine

#### Version control
- Git
- GitHub.com
- Git Large File System

#### Databases
- TODO the db in carpentries
- PostgreSQL database language (queries, import and export of data) 
- pgAdmin III database interface and psql command line interface for use with PostgreSQL 
- LibreOffice 3.4+ Base 
- Microsoft Access (uses jetSQL)

### Citation/reference management
- Zotero 3.0.7+ bibliography software

### Word Processing and Spreadsheets
- Microsoft Office 365: Word, Access, Excel, PowerPoint, OneNote
- LibreOffice 3.3.0+: Writer, Impress (PowerPoint equivalent), Base (Access equivalent)

### Specialized Software
- Raven Pro 1.5 sound analysis software
- Phylogenetic software (basic procedures): MRBAYES 3.1.2, RAxML, GARLI 1.0, FigTree, and MEGA 4.0
